"""Textos legales fijos del Cartography Engine (advertencias, notas)."""

from __future__ import annotations

ADVERTENCIA_TEXT = (
    "LA INFORMACIÓN CARTOGRÁFICA FUE ELABORADA A PARTIR DEL MARCO "
    "GEOSTADÍSTICO NACIONAL ÚNICO, IMPLEMENTADO POR EL INEGI. LOS LÍMITES DE LAS "
    "ÁREAS GEOESTADÍSTICAS (AGEE, AGEM Y AGEB) SE BASAN EN RASGOS FÍSICOS DEL "
    "TERRENO Y, EN SU CASO, EN LINDEROS POLÍTICO-ADMINISTRATIVOS. NO CONSTITUYEN "
    "DEFINICIÓN OFICIAL DE LÍMITES ESTATALES, MUNICIPALES O PROPIEDAD PRIVADA. "
    "FECHA DE ACTUALIZACIÓN: DICIEMBRE DEL 2024."
)
